<?php  
error_reporting(E_ERROR | E_WARNING | E_PARSE);
$db = pg_connect("host=localhost port=5432 dbname=winsig user=postgres password=root"); 
echo 'Capacidad: ' . $_POST[capacidad];
echo "<br>";
$id_fh = $_POST['selectid_fh'];
echo "Tipo FH: " . $id_fh;
echo "<br>";
echo 'latitud: ' . $_POST[latitud];
echo "<br>";
echo 'longitud: ' . $_POST[longitud];
echo "<br>";
echo 'selectid_municipio: ' . $_POST[selectid_municipio];
echo "<br>";
$id_m = $_POST['selectid_municipio'];
echo "id Minicipio: " . $id_m;
echo "<br>";
echo 'va_od: ' . $_POST[va_od];
echo "<br>";
echo 'va_sst: ' . $_POST[va_sst];
echo "<br>";
echo 'va_dqo: ' . $_POST[va_dqo];
echo "<br>";
echo 'va_ce: ' . $_POST[va_ce];
echo "<br>";
echo 'va_ph: ' . $_POST[va_ph];
echo "<br>";
echo 'acc_agua: ' . $_POST[acc_agua];
echo "<br>";
echo 'acce_sani: ' . $_POST[acce_sani];
echo "<br>";
echo 'acc_irri: ' . $_POST[acc_irri];
echo "<br>";
echo 'nom_comunidad: ' . $_POST[nom_comunidad];
echo "<br>";
echo 'cantidad_personas: ' . $_POST[cantidad_personas];
echo "<br>";
echo 'representante: ' . $_POST[representante];
?>